BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.Data;
using BulkyBook.DataAccess.IRepository;
using BulkyBook.DataAccess.Repository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Reflection;

namespace BulkyBookWeb.Areas.Admin.Controllers;
[Area("Admin")]
public class CategoryController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public CategoryController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
    }

    public IActionResult Index()
    {
        IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
        return View(objCategoryList);
    }

    //GET
    public IActionResult Create()
    {
        return View();
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category obj)
    {
        if (obj.Name == obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
        }
        if (ModelState.IsValid)
        {
            _unitOfWork.Category.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET
    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        //var categoryFromDb = _category.Categories.Find(id);
        var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
        //var categoryFromDbSingle = _category.Categories.SingleOrDefault(u => u.Id == id);

        if (categoryFromDbFirst == null)
        {
            return NotFound();
        }

        return View(categoryFromDbFirst);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Category obj)
    {
        if (obj.Name == obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
        }
        if (ModelState.IsValid)
        {
            _unitOfWork.Category.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category updated successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

        if (categoryFromDbFirst == null)
        {
            return NotFound();
        }

        return View(categoryFromDbFirst);
    }

    //POST
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(int? id)
    {
        var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOfWork.Category.Remove(obj);
        _unitOfWork.Save();
        TempData["success"] = "Category deleted successfully";
        return RedirectToAction("Index");

    }

}

BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> coverTypes = _unitOfWork.CoverType.GetAll();
            return View(coverTypes);
        }

        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Cover Type created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);

            if (coverTypeFromDbFirst == null)
            {
                return NotFound();
            }
            return View(coverTypeFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Cover Type updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (coverTypeFromDbFirst == null)
            {
                return NotFound();
            }
            _unitOfWork.CoverType.Remove(coverTypeFromDbFirst);
            _unitOfWork.Save();
            TempData["success"] = "Cover Type deleted successfully";
            return RedirectToAction("Index");
        }

    }
}

BulkyBookWeb/Areas/Admin/Controllers/ReportController.cs
using BulkyBook.DataAccess.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Reporting.NETCore;
using Microsoft.ReportingServices.ReportProcessing.ReportObjectModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReportController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ReportController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DemoReport1Download()
        {
            IEnumerable<Employee> objEmployeeList = _unitOfWork.Employee.GetAll();
            var path = $"{this._webHostEnvironment.WebRootPath}\\Reports\\rptControlsDemo.rdlc";
            LocalReport report = new LocalReport();
            report.ReportPath = path;
            IEnumerable<ReportParameter> parameters = new[] { new ReportParameter("reportHeading", "Employee List") };
            ReportDataSource dataSource = new ReportDataSource("rptControlsDemoDto", objEmployeeList);
            report.SetParameters(parameters);
            report.DataSources.Add(dataSource);
            byte[] pdfData = report.Render("PDF");
            return File(pdfData, "application/pdf", "report.pdf");
        }

        public IActionResult DemoReport2Download()
        {
            IEnumerable<FeeCollection> objFeeCollectionList = _unitOfWork.FeeCollection.GetAll();
            var path = $"{this._webHostEnvironment.WebRootPath}\\Reports\\rptMatrixReport.rdlc";
            LocalReport report = new LocalReport();
            report.ReportPath = path;
            IEnumerable<ReportParameter> parameters = new[] { new ReportParameter("reportHeading", "Fee Collection List") };
            ReportDataSource dataSource = new ReportDataSource("rptMatrixReportDto", objFeeCollectionList);
            report.SetParameters(parameters);
            report.DataSources.Add(dataSource);
            byte[] pdfData = report.Render("PDF");
            return File(pdfData, "application/pdf", "report.pdf");
        }

        public IActionResult DemoReport3Download()
        {
            IEnumerable<Employee> objEmployeeList = _unitOfWork.Employee.GetAll();
            var path = $"{this._webHostEnvironment.WebRootPath}\\Reports\\rptChartReport.rdlc";
            LocalReport report = new LocalReport();
            report.ReportPath = path;
            IEnumerable<ReportParameter> parameters = new[] { new ReportParameter("reportHeading", "City Wise Employee Chart") };
            ReportDataSource dataSource = new ReportDataSource("rptControlDemoDto", objEmployeeList);
            report.SetParameters(parameters);
            report.DataSources.Add(dataSource);
            byte[] pdfData = report.Render("PDF");
            return File(pdfData, "application/pdf", "report.pdf");
        }       

        public IActionResult DemoReport4Download()
        {
            IEnumerable<Employee> objEmployeeList = _unitOfWork.Employee.GetAll();
            var path = $"{this._webHostEnvironment.WebRootPath}\\Reports\\rptEmployeeReport.rdlc";
            LocalReport report = new LocalReport();
            report.ReportPath = path;
            IEnumerable<ReportParameter> parameters = new[] { new ReportParameter("reportHeading", "Employee List") };
            ReportDataSource dataSource = new ReportDataSource("rptEmployeeDto", objEmployeeList);
            report.SetParameters(parameters);
            report.DataSources.Add(dataSource);

            #region Sub Report
            report.SubreportProcessing += new SubreportProcessingEventHandler(SubReportProccessing);
            #endregion

            byte[] pdfData = report.Render("PDF");
            return File(pdfData, "application/pdf", "report.pdf");
        }

        public IActionResult DemoReport5Download()
        {
            IEnumerable<Employee> objEmployeeList = _unitOfWork.Employee.GetAll();
            var path = $"{this._webHostEnvironment.WebRootPath}\\Reports\\rptListControl.rdlc";
            LocalReport report = new LocalReport();
            report.ReportPath = path;
            IEnumerable<ReportParameter> parameters = new[] { new ReportParameter("reportHeading", "List Control Demo") };
            ReportDataSource dataSource = new ReportDataSource("rptControlsDemoDto", objEmployeeList);
            report.SetParameters(parameters);
            report.DataSources.Add(dataSource);
            byte[] pdfData = report.Render("PDF");
            return File(pdfData, "application/pdf", "report.pdf");
        }

        public IActionResult DemoReport6Download()
        {
            IEnumerable<FeeCollection> objFeeCollectionList = _unitOfWork.FeeCollection.GetAll();
            var path = $"{this._webHostEnvironment.WebRootPath}\\Reports\\rptGauge.rdlc";
            LocalReport report = new LocalReport();
            report.ReportPath = path;
            IEnumerable<ReportParameter> parameters = new[] { new ReportParameter("reportHeading", "Gauge Demo") };
            ReportDataSource dataSource = new ReportDataSource("rptMatrixReportDto", objFeeCollectionList);
            report.SetParameters(parameters);
            report.DataSources.Add(dataSource);
            byte[] pdfData = report.Render("PDF");
            return File(pdfData, "application/pdf", "report.pdf");
        }

        void SubReportProccessing(object sender,SubreportProcessingEventArgs e)
        {
            int EmpId = Convert.ToInt32(e.Parameters["EmpId"].Values[0]);
            IEnumerable<Employee> objEmployeeDetails = _unitOfWork.Employee.GetAll().Where(x=>x.Id == EmpId);
            ReportDataSource dataSource = new ReportDataSource("rptEmployeeDetailsDto", objEmployeeDetails);
            e.DataSources.Add(dataSource);
        }
    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Report" asp-action="Index">Report</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2021 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}